server:
  port: ${PORT:9080}

spring:
  application:
    name: ${SERVICE_NAME:test-education-project}
  datasource:
    url: jdbc:postgresql://localhost:5432/solarl
    username: user
    password: password
    driver-class-name: org.postgresql.Driver
  flyway:
    enabled: true
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:9090/realms/master
          jwk-set-uri: http://localhost:9090/realms/master/protocol/openid-connect/certs

logging:
  level:
    org.springframework: ${LOGGING_LEVEL_SPRING:INFO}
    org.springframework.security: DEBUG

jwt:
  auth:
    converter:
      resource-id: account
      principle-attribute: preferred_username

notification:
  telegram: false

super:
  duper:
    test:
      phrase: "Hello, World!"
