apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
  namespace: solarlab
data:
  SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/solarl
  SPRING_DATASOURCE_USERNAME: user
  SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_ISSUER_URI: http://keycloak:8080/realms/master
  SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_JWK_SET_URI: http://keycloak:8080/realms/master/protocol/openid-connect/certs
