apiVersion: v1
kind: Secret
metadata:
  name: app-secrets
  namespace: solarlab
type: Opaque
stringData:
  SPRING_DATASOURCE_PASSWORD: password
---
apiVersion: v1
kind: Secret
metadata:
  name: postgres-secrets
  namespace: solarlab
type: Opaque
stringData:
  POSTGRES_PASSWORD: password
---
apiVersion: v1
kind: Secret
metadata:
  name: keycloak-secrets
  namespace: solarlab
type: Opaque
stringData:
  KEYCLOAK_ADMIN: admin
  KEYCLOAK_ADMIN_PASSWORD: password
