apiVersion: v1
kind: Service
metadata:
  name: postgres
  namespace: solarlab
spec:
  selector:
    app: postgres
  ports:
    - name: postgres
      port: 5432
      targetPort: 5432
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: keycloak
  namespace: solarlab
spec:
  selector:
    app: keycloak
  ports:
    - name: http
      port: 8080
      targetPort: 8080
      nodePort: 30090
  type: NodePort
---
apiVersion: v1
kind: Service
metadata:
  name: app
  namespace: solarlab
spec:
  selector:
    app: app
  ports:
    - name: http
      port: 9080
      targetPort: 9080
      nodePort: 30080
  type: NodePort
